# Hallucination Detection Pipeline
This notebook runs the full pipeline on Google Colab with a free T4 GPU:
1. **Setup** — Install dependencies, upload dataset, login to HuggingFace
2. **Extract** — Run LLM forward passes and save per-layer hidden state features
3. **Probe** — Train logistic regression probes on each layer
4. **Ablation** — Train/test probes across domains
5. **Geometric** — PCA visualization and distance analysis

**Before running:** Set runtime to GPU via `Runtime > Change runtime type > T4 GPU`

todos:

1. Address overfitting with the linear regression model
    1. First, start with different penalties (likely wouldn’t change anything) / Try Elastic Net?
    2. Ensemble classification w/ boosted linear regression?
2. Add MLP to check if there’s a non-linear signal between them
3. Add PCA and try linear regression that way
4. If none of these work, then we see that there’s likely no separability between logistic regression and what
5. If there is separability, then we want to see in particular, if hallucinations cluster at all… but hallucinations is a probabalistic thing, right? What’s a plan to check for hallucinations and see if they’re different from anything else



```
# This is formatted as code
```

todos:

1. Address overfitting with the linear regression model
    1. First, start with different penalties (likely wouldn’t change anything) / Try Elastic Net?
    2. Ensemble classification w/ boosted linear regression?
2. Add MLP to check if there’s a non-linear signal between them
3. Add PCA and try linear regression that way
4. If none of these work, then we see that there’s likely no separability between logistic regression and what
5. If there is separability, then we want to see in particular, if hallucinations cluster at all… but hallucinations is a probabalistic thing, right? What’s a plan to check for hallucinations and see if they’re different from

## Step 0: Setup

In [ ]:
!pip install -q torch transformers accelerate pandas pyarrow scikit-learn matplotlib huggingface_hub bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 41.4 MB/s eta 0:00:00

In [ ]:
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    props = torch.cuda.get_device_properties(0)
    print(f"VRAM: {props.total_memory / 1e9:.1f} GB")

CUDA available: True
GPU: Tesla T4
VRAM: 15.6 GB

In [ ]:
from huggingface_hub import login
login()  # paste your HuggingFace token when prompted

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
from google.colab import files
print("Upload your dataset.parquet file:")
uploaded = files.upload()
DATASET_PATH = list(uploaded.keys())[0]
print(f"Uploaded: {DATASET_PATH}")

Upload your dataset.parquet file:

Saving dataset.parquet to dataset.parquet
Uploaded: dataset.parquet

In [ ]:
# ---- CONFIG ----
MODEL_NAME = "meta-llama/Llama-2-13b-hf"   # change to any HF model
FEATURES_DIR = "features"
BATCH_SIZE = 4
MAX_LENGTH = 256
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
PROMPT_TEMPLATE = "Answer True/False and explain briefly: {statement}"
PROBE_C = 1.0
TEST_SIZE = 0.2
SEED = 42
N_PAIRS = 10000
COV_REG = 1e-4
USE_4BIT = False  # 4-bit quantization — required for 13B models on T4 (16 GB VRAM)

print(f"Model: {MODEL_NAME}")
print(f"Device: {DEVICE}")
print(f"4-bit quantization: {USE_4BIT}")
print(f"Batch size: {BATCH_SIZE}")

Model: meta-llama/Llama-2-13b-hf
Device: cuda
4-bit quantization: False
Batch size: 4

## Step 1: Extract Features
Run forward passes through the LLM and save hidden state activations for each layer.

In [ ]:
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import pandas as pd
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig


def _infer_input_device(model, fallback_device: str) -> torch.device:
    """ Just sets up CUDA shenanigans """
    if hasattr(model, "hf_device_map") and isinstance(model.hf_device_map, dict):
        for key in ["model.embed_tokens", "embed_tokens", "lm_head"]:
            if key in model.hf_device_map:
                dev = model.hf_device_map[key]
                if isinstance(dev, int):
                    return torch.device(f"cuda:{dev}")
                return torch.device(str(dev))
        first_dev = next(iter(model.hf_device_map.values()), None)
        if first_dev is not None:
            if isinstance(first_dev, int):
                return torch.device(f"cuda:{first_dev}")
            return torch.device(str(first_dev))
    return torch.device(fallback_device)


def extract_features(model_name, dataset_path, out_dir, batch_size, max_length, device, prompt_template, use_4bit=False):
    """ Reads data from dataset.parquet, """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    df = pd.read_parquet(dataset_path)
    required = {"id", "domain", "label", "statement"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns: {', '.join(sorted(missing))}")

    texts = [prompt_template.format(statement=str(s)) for s in df["statement"].tolist()]
    labels = df["label"].astype(int).to_numpy()
    domains = df["domain"].astype(str).to_numpy()
    ids = df["id"].astype(str).to_numpy()
    print(f"Loaded {len(texts)} examples")

    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    dtype = torch.float16 if device.startswith("cuda") else torch.float32

    if use_4bit and device.startswith("cuda"):
        print("Loading model with 4-bit quantization (NF4)...")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            model_name, quantization_config=bnb_config, output_hidden_states=True, device_map="auto",
        )
    elif device.startswith("cuda"):
        print(f"Loading model in {dtype}...")
        model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=dtype, output_hidden_states=True, device_map="auto")
    else:
        print(f"Loading model in {dtype}...")
        model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=dtype, output_hidden_states=True)
        model.to(device)
    model.eval()
    input_device = _infer_input_device(model, fallback_device=device)
    print(f"Model loaded. Input device: {input_device}")

    sample = tokenizer("test", return_tensors="pt")
    sample = {k: v.to(input_device) for k, v in sample.items()}
    with torch.no_grad():
        out = model(**sample)
    num_layers = len(out.hidden_states)
    hidden_dim = out.hidden_states[0].shape[-1]
    print(f"Detected {num_layers} layers, hidden_dim={hidden_dim}")

    feats_by_layer = [[] for _ in range(num_layers)]
    total_batches = (len(texts) + batch_size - 1) // batch_size

    for batch_num, i in enumerate(range(0, len(texts), batch_size)):
        if batch_num % 20 == 0:
            print(f"  Batch {batch_num + 1}/{total_batches}")
        batch_texts = texts[i : i + batch_size]
        enc = tokenizer(batch_texts, return_tensors="pt", padding=True, truncation=True, max_length=max_length)
        enc = {k: v.to(input_device) for k, v in enc.items()}

        with torch.no_grad():
            out = model(**enc)
            hs = out.hidden_states

        attn = enc["attention_mask"]
        last_idx = (attn.sum(dim=1) - 1).clamp(min=0)
        batch_idx = torch.arange(last_idx.shape[0], device=last_idx.device)

        for layer_idx in range(num_layers):
            h_last = hs[layer_idx][batch_idx, last_idx, :]
            feats_by_layer[layer_idx].append(h_last.detach().float().cpu().numpy())

    print("Saving features...")
    meta = {
        "model_name": model_name, "num_layers": num_layers, "hidden_dim": hidden_dim,
        "n_examples": len(texts), "max_length": max_length, "batch_size": batch_size,
        "device": device, "prompt_template": prompt_template,
        "layer_0_is_embedding_output": True, "feature_dtype": "float32",
    }
    with (out_path / "meta.json").open("w") as f:
        json.dump(meta, f, indent=2)

    np.savez_compressed(out_path / "labels_domains_ids.npz", y=labels, domain=domains, id=ids)
    for layer_idx in range(num_layers):
        x = np.concatenate(feats_by_layer[layer_idx], axis=0)
        np.savez_compressed(out_path / f"layer_{layer_idx:02d}.npz", X=x)
        print(f"  Saved layer_{layer_idx:02d}.npz  shape={x.shape}")

    print(f"\nExtraction complete. {num_layers} layers saved to {out_dir}/")
    return num_layers, hidden_dim

In [ ]:
num_layers, hidden_dim = extract_features(
    model_name=MODEL_NAME,
    dataset_path=DATASET_PATH,
    out_dir=FEATURES_DIR,
    batch_size=BATCH_SIZE,
    max_length=MAX_LENGTH,
    device=DEVICE,
    prompt_template=PROMPT_TEMPLATE,
    use_4bit=USE_4BIT,
)

Loaded 9427 examples

config.json:   0%|          | 0.00/610 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

Loading model in torch.float16...

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['output_hidden_states']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loading weights:   0%|          | 0/363 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.

Model loaded. Input device: cuda:0
Detected 41 layers, hidden_dim=5120
  Batch 1/2357
  Batch 21/2357
  Batch 41/2357
  Batch 61/2357
  Batch 81/2357
  Batch 101/2357
  Batch 121/2357
  Batch 141/2357
  Batch 161/2357
  Batch 181/2357
  Batch 201/2357
  Batch 221/2357
  Batch 241/2357
  Batch 261/2357
  Batch 281/2357
  Batch 301/2357
  Batch 321/2357
  Batch 341/2357
  Batch 361/2357
  Batch 381/2357
  Batch 401/2357
  Batch 421/2357
  Batch 441/2357
  Batch 461/2357
  Batch 481/2357
  Batch 501/2357
  Batch 521/2357
  Batch 541/2357
  Batch 561/2357
  Batch 581/2357
  Batch 601/2357
  Batch 621/2357
  Batch 641/2357
  Batch 661/2357
  Batch 681/2357
  Batch 701/2357
  Batch 721/2357
  Batch 741/2357
  Batch 761/2357
  Batch 781/2357
  Batch 801/2357
  Batch 821/2357
  Batch 841/2357
  Batch 861/2357
  Batch 881/2357
  Batch 901/2357
  Batch 921/2357
  Batch 941/2357
  Batch 961/2357
  Batch 981/2357
  Batch 1001/2357
  Batch 1021/2357
  Batch 1041/2357
  Batch 1061/2357
  Batch 1081/2357
  Batch 1101/2357
  Batch 1121/2357
  Batch 1141/2357
  Batch 1161/2357
  Batch 1181/2357
  Batch 1201/2357
  Batch 1221/2357
  Batch 1241/2357
  Batch 1261/2357
  Batch 1281/2357
  Batch 1301/2357
  Batch 1321/2357
  Batch 1341/2357
  Batch 1361/2357
  Batch 1381/2357
  Batch 1401/2357
  Batch 1421/2357
  Batch 1441/2357
  Batch 1461/2357
  Batch 1481/2357
  Batch 1501/2357
  Batch 1521/2357
  Batch 1541/2357
  Batch 1561/2357
  Batch 1581/2357
  Batch 1601/2357
  Batch 1621/2357
  Batch 1641/2357
  Batch 1661/2357
  Batch 1681/2357
  Batch 1701/2357
  Batch 1721/2357
  Batch 1741/2357
  Batch 1761/2357
  Batch 1781/2357
  Batch 1801/2357
  Batch 1821/2357
  Batch 1841/2357
  Batch 1861/2357
  Batch 1881/2357
  Batch 1901/2357
  Batch 1921/2357
  Batch 1941/2357
  Batch 1961/2357
  Batch 1981/2357
  Batch 2001/2357
  Batch 2021/2357
  Batch 2041/2357
  Batch 2061/2357
  Batch 2081/2357
  Batch 2101/2357
  Batch 2121/2357
  Batch 2141/2357
  Batch 2161/2357
  Batch 2181/2357
  Batch 2201/2357
  Batch 2221/2357
  Batch 2241/2357
  Batch 2261/2357
  Batch 2281/2357
  Batch 2301/2357
  Batch 2321/2357
  Batch 2341/2357
Saving features...
  Saved layer_00.npz  shape=(9427, 5120)
  Saved layer_01.npz  shape=(9427, 5120)
  Saved layer_02.npz  shape=(9427, 5120)
  Saved layer_03.npz  shape=(9427, 5120)
  Saved layer_04.npz  shape=(9427, 5120)
  Saved layer_05.npz  shape=(9427, 5120)
  Saved layer_06.npz  shape=(9427, 5120)
  Saved layer_07.npz  shape=(9427, 5120)
  Saved layer_08.npz  shape=(9427, 5120)
  Saved layer_09.npz  shape=(9427, 5120)
  Saved layer_10.npz  shape=(9427, 5120)
  Saved layer_11.npz  shape=(9427, 5120)
  Saved layer_12.npz  shape=(9427, 5120)
  Saved layer_13.npz  shape=(9427, 5120)
  Saved layer_14.npz  shape=(9427, 5120)
  Saved layer_15.npz  shape=(9427, 5120)
  Saved layer_16.npz  shape=(9427, 5120)
  Saved layer_17.npz  shape=(9427, 5120)
  Saved layer_18.npz  shape=(9427, 5120)
  Saved layer_19.npz  shape=(9427, 5120)
  Saved layer_20.npz  shape=(9427, 5120)
  Saved layer_21.npz  shape=(9427, 5120)
  Saved layer_22.npz  shape=(9427, 5120)
  Saved layer_23.npz  shape=(9427, 5120)
  Saved layer_24.npz  shape=(9427, 5120)
  Saved layer_25.npz  shape=(9427, 5120)
  Saved layer_26.npz  shape=(9427, 5120)
  Saved layer_27.npz  shape=(9427, 5120)
  Saved layer_28.npz  shape=(9427, 5120)
  Saved layer_29.npz  shape=(9427, 5120)
  Saved layer_30.npz  shape=(9427, 5120)
  Saved layer_31.npz  shape=(9427, 5120)
  Saved layer_32.npz  shape=(9427, 5120)
  Saved layer_33.npz  shape=(9427, 5120)
  Saved layer_34.npz  shape=(9427, 5120)
  Saved layer_35.npz  shape=(9427, 5120)
  Saved layer_36.npz  shape=(9427, 5120)
  Saved layer_37.npz  shape=(9427, 5120)
  Saved layer_38.npz  shape=(9427, 5120)
  Saved layer_39.npz  shape=(9427, 5120)
  Saved layer_40.npz  shape=(9427, 5120)

Extraction complete. 41 layers saved to features/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import shutil
!cp -r "/content/features" "/content/drive/MyDrive/features"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Step 2: Layer Sweep (Probe Training)
Train a logistic regression probe on each layer and evaluate accuracy + AUROC.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score


def train_logreg_probe(X_train, y_train, C=1.0):
    clf = LogisticRegression(penalty="l2", C=C, solver="liblinear", max_iter=2000, class_weight="balanced")
    clf.fit(X_train, y_train)
    return clf


def eval_binary_classifier(clf, X, y):
    probs = clf.predict_proba(X)[:, 1]
    preds = (probs >= 0.5).astype(int)
    metrics = {"acc": float(accuracy_score(y, preds))}
    try:
        metrics["auroc"] = float(roc_auc_score(y, probs))
    except ValueError:
        metrics["auroc"] = float("nan")
    return metrics


def build_train_test_indices(n, test_size, seed):
    rng = np.random.RandomState(seed)
    shuffled = np.arange(n)
    rng.shuffle(shuffled)
    n_test = max(1, min(n - 1, int(round(n * test_size))))
    return shuffled[n_test:], shuffled[:n_test]


def run_layer_sweep(features_dir, test_size, seed, C):
    features_path = Path(features_dir)
    shared = np.load(features_path / "labels_domains_ids.npz", allow_pickle=True)
    y = shared["y"]

    train_idx, test_idx = build_train_test_indices(len(y), test_size, seed)

    layer_files = sorted(features_path.glob("layer_*.npz"), key=lambda p: int(p.stem.split("_")[1]))
    print(f"Found {len(layer_files)} layer files, n_train={len(train_idx)}, n_test={len(test_idx)}")

    rows = []
    for layer_file in layer_files:
        layer_idx = int(layer_file.stem.split("_")[1])
        X = np.load(layer_file)["X"]

        clf = train_logreg_probe(X[train_idx], y[train_idx], C=C)
        train_m = eval_binary_classifier(clf, X[train_idx], y[train_idx])
        test_m = eval_binary_classifier(clf, X[test_idx], y[test_idx])

        row = {
            "layer": layer_idx, "n_train": len(train_idx), "n_test": len(test_idx),
            "train_acc": train_m["acc"], "train_auroc": train_m["auroc"],
            "test_acc": test_m["acc"], "test_auroc": test_m["auroc"],
        }
        rows.append(row)
        print(f"  layer={layer_idx:02d}  train_acc={row['train_acc']:.4f}  train_auroc={row['train_auroc']:.4f}  test_acc={row['test_acc']:.4f}  test_auroc={row['test_auroc']:.4f}")

    return pd.DataFrame(rows).sort_values("layer").reset_index(drop=True)

In [ ]:
sweep_df = run_layer_sweep(FEATURES_DIR, test_size=TEST_SIZE, seed=SEED, C=PROBE_C)

best_row = sweep_df.loc[sweep_df["test_auroc"].idxmax()]
BEST_LAYER = int(best_row["layer"])
print(f"\nBest layer: {BEST_LAYER} (test_auroc={best_row['test_auroc']:.4f})")

sweep_df.to_csv("layer_sweep_results.csv", index=False)
print("Saved layer_sweep_results.csv")
sweep_df

Found 41 layer files, n_train=7542, n_test=1885
  layer=00  train_acc=0.6946  train_auroc=0.7623  test_acc=0.5496  test_auroc=0.5627
  layer=01  train_acc=0.7058  train_auroc=0.7916  test_acc=0.5570  test_auroc=0.5691
  layer=02  train_acc=0.7629  train_auroc=0.8613  test_acc=0.5639  test_auroc=0.5729
  layer=03  train_acc=0.8347  train_auroc=0.9267  test_acc=0.5602  test_auroc=0.5578
  layer=04  train_acc=0.8828  train_auroc=0.9598  test_acc=0.5698  test_auroc=0.5822
  layer=05  train_acc=0.9100  train_auroc=0.9737  test_acc=0.5814  test_auroc=0.5795
  layer=06  train_acc=0.9287  train_auroc=0.9850  test_acc=0.5729  test_auroc=0.5762
  layer=07  train_acc=0.9527  train_auroc=0.9912  test_acc=0.5830  test_auroc=0.5883
  layer=08  train_acc=0.9663  train_auroc=0.9953  test_acc=0.5756  test_auroc=0.5817
  layer=09  train_acc=0.9739  train_auroc=0.9972  test_acc=0.5841  test_auroc=0.5847
  layer=10  train_acc=0.9850  train_auroc=0.9983  test_acc=0.5889  test_auroc=0.5964
  layer=11  train_acc=0.9893  train_auroc=0.9992  test_acc=0.5995  test_auroc=0.5958
  layer=12  train_acc=0.9915  train_auroc=0.9996  test_acc=0.6154  test_auroc=0.6241
  layer=13  train_acc=0.9940  train_auroc=0.9996  test_acc=0.6117  test_auroc=0.6304
  layer=14  train_acc=0.9956  train_auroc=0.9999  test_acc=0.6218  test_auroc=0.6394
  layer=15  train_acc=0.9963  train_auroc=1.0000  test_acc=0.6265  test_auroc=0.6372
  layer=16  train_acc=0.9968  train_auroc=1.0000  test_acc=0.6286  test_auroc=0.6428
  layer=17  train_acc=0.9981  train_auroc=1.0000  test_acc=0.6525  test_auroc=0.6589
  layer=18  train_acc=0.9980  train_auroc=1.0000  test_acc=0.6483  test_auroc=0.6569
  layer=19  train_acc=0.9984  train_auroc=1.0000  test_acc=0.6292  test_auroc=0.6498
  layer=20  train_acc=0.9988  train_auroc=1.0000  test_acc=0.6276  test_auroc=0.6501
  layer=21  train_acc=0.9989  train_auroc=1.0000  test_acc=0.6122  test_auroc=0.6257
  layer=22  train_acc=0.9989  train_auroc=1.0000  test_acc=0.6233  test_auroc=0.6388
  layer=23  train_acc=0.9992  train_auroc=1.0000  test_acc=0.6228  test_auroc=0.6367
  layer=24  train_acc=0.9995  train_auroc=1.0000  test_acc=0.6138  test_auroc=0.6308
  layer=25  train_acc=0.9995  train_auroc=1.0000  test_acc=0.6223  test_auroc=0.6339
  layer=26  train_acc=0.9996  train_auroc=1.0000  test_acc=0.6233  test_auroc=0.6255
  layer=27  train_acc=0.9999  train_auroc=1.0000  test_acc=0.6175  test_auroc=0.6215
  layer=28  train_acc=0.9999  train_auroc=1.0000  test_acc=0.6143  test_auroc=0.6153
  layer=29  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6074  test_auroc=0.6039
  layer=30  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6085  test_auroc=0.6110
  layer=31  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6207  test_auroc=0.6200
  layer=32  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6212  test_auroc=0.6186
  layer=33  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6138  test_auroc=0.6217
  layer=34  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6159  test_auroc=0.6222
  layer=35  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6143  test_auroc=0.6204
  layer=36  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6122  test_auroc=0.6225
  layer=37  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6122  test_auroc=0.6167
  layer=38  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6159  test_auroc=0.6239
  layer=39  train_acc=1.0000  train_auroc=1.0000  test_acc=0.6127  test_auroc=0.6283
  layer=40  train_acc=0.9992  train_auroc=1.0000  test_acc=0.6191  test_auroc=0.6282

Best layer: 17 (test_auroc=0.6589)
Saved layer_sweep_results.csv

    layer  n_train  n_test  train_acc  train_auroc  test_acc  test_auroc
0       0     7542    1885   0.694643     0.762335  0.549602    0.562712
1       1     7542    1885   0.705781     0.791604  0.557029    0.569129
2       2     7542    1885   0.762928     0.861275  0.563926    0.572904
3       3     7542    1885   0.834659     0.926711  0.560212    0.557798
4       4     7542    1885   0.882790     0.959794  0.569761    0.582217
5       5     7542    1885   0.909971     0.973705  0.581432    0.579453
6       6     7542    1885   0.928666     0.984988  0.572944    0.576183
7       7     7542    1885   0.952665     0.991177  0.583024    0.588336
8       8     7542    1885   0.966322     0.995322  0.575597    0.581669
9       9     7542    1885   0.973880     0.997241  0.584085    0.584670
10     10     7542    1885   0.985017     0.998252  0.588859    0.596434
11     11     7542    1885   0.989260     0.999159  0.599469    0.595780
12     12     7542    1885   0.991514     0.999569  0.615385    0.624070
13     13     7542    1885   0.994033     0.999627  0.611671    0.630378
14     14     7542    1885   0.995625     0.999855  0.621751    0.639393
15     15     7542    1885   0.996287     0.999975  0.626525    0.637239
16     16     7542    1885   0.996818     0.999966  0.628647    0.642832
17     17     7542    1885   0.998144     0.999990  0.652520    0.658947
18     18     7542    1885   0.998011     0.999982  0.648276    0.656892
19     19     7542    1885   0.998409     0.999978  0.629178    0.649777
20     20     7542    1885   0.998807     0.999995  0.627586    0.650139
21     21     7542    1885   0.998939     0.999998  0.612202    0.625706
22     22     7542    1885   0.998939     1.000000  0.623342    0.638847
23     23     7542    1885   0.999204     0.999999  0.622812    0.636724
24     24     7542    1885   0.999470     0.999998  0.613793    0.630794
25     25     7542    1885   0.999470     0.999999  0.622281    0.633887
26     26     7542    1885   0.999602     1.000000  0.623342    0.625467
27     27     7542    1885   0.999867     1.000000  0.617507    0.621518
28     28     7542    1885   0.999867     1.000000  0.614324    0.615281
29     29     7542    1885   1.000000     1.000000  0.607427    0.603853
30     30     7542    1885   1.000000     1.000000  0.608488    0.611037
31     31     7542    1885   1.000000     1.000000  0.620690    0.619963
32     32     7542    1885   1.000000     1.000000  0.621220    0.618560
33     33     7542    1885   1.000000     1.000000  0.613793    0.621665
34     34     7542    1885   1.000000     1.000000  0.615915    0.622212
35     35     7542    1885   1.000000     1.000000  0.614324    0.620399
36     36     7542    1885   1.000000     1.000000  0.612202    0.622508
37     37     7542    1885   1.000000     1.000000  0.612202    0.616662
38     38     7542    1885   1.000000     1.000000  0.615915    0.623881
39     39     7542    1885   1.000000     1.000000  0.612732    0.628290
40     40     7542    1885   0.999204     0.999982  0.619098    0.628162

## Step 3: Domain Ablation
Train on one domain, test on another (or same) domain for each layer.

In [ ]:
def run_domain_ablation(features_dir, C):
    features_path = Path(features_dir)
    shared = np.load(features_path / "labels_domains_ids.npz", allow_pickle=True)
    y = shared["y"]
    domains = shared["domain"]

    unique_domains = list(dict.fromkeys(str(d) for d in domains))
    print(f"Domains found: {unique_domains}")

    layer_files = sorted(features_path.glob("layer_*.npz"), key=lambda p: int(p.stem.split("_")[1]))
    rows = []

    for layer_file in layer_files:
        layer_idx = int(layer_file.stem.split("_")[1])
        X = np.load(layer_file)["X"]

        for train_d in unique_domains:
            for test_d in unique_domains:
                train_mask = domains == train_d
                test_mask = domains == test_d

                clf = train_logreg_probe(X[train_mask], y[train_mask], C=C)
                in_m = eval_binary_classifier(clf, X[train_mask], y[train_mask])
                cross_m = eval_binary_classifier(clf, X[test_mask], y[test_mask])

                rows.append({
                    "layer": layer_idx, "train_domain": train_d, "test_domain": test_d,
                    "n_train": int(train_mask.sum()), "n_test": int(test_mask.sum()),
                    "in_acc": in_m["acc"], "in_auroc": in_m["auroc"],
                    "cross_acc": cross_m["acc"], "cross_auroc": cross_m["auroc"],
                })

        print(f"  layer={layer_idx:02d} done")

    return pd.DataFrame(rows).sort_values(["layer", "train_domain", "test_domain"]).reset_index(drop=True)

In [ ]:
ablation_df = run_domain_ablation(FEATURES_DIR, C=PROBE_C)
ablation_df.to_csv("domain_ablation_results.csv", index=False)
print("Saved domain_ablation_results.csv")
ablation_df

Domains found: ['boolq']
  layer=00 done
  layer=01 done
  layer=02 done
  layer=03 done
  layer=04 done
  layer=05 done
  layer=06 done
  layer=07 done
  layer=08 done
  layer=09 done
  layer=10 done
  layer=11 done
  layer=12 done
  layer=13 done

KeyboardInterrupt:

## Step 4: Geometric Evaluation
PCA visualization and distance analysis on the best layer.

In [ ]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt


def sample_pairs(a_idx, b_idx, n_pairs, seed):
    rng = np.random.RandomState(seed)
    pairs, seen = [], set()
    if len(a_idx) == 0 or len(b_idx) == 0:
        return pairs
    for _ in range(n_pairs * 10 + 100):
        if len(pairs) >= n_pairs:
            break
        i = int(a_idx[rng.randint(0, len(a_idx))])
        j = int(b_idx[rng.randint(0, len(b_idx))])
        if i == j:
            continue
        key = (min(i, j), max(i, j))
        if key not in seen:
            seen.add(key)
            pairs.append(key)
    return pairs


def cosine_distance(x, y):
    denom = float(np.linalg.norm(x) * np.linalg.norm(y))
    if denom <= 1e-12:
        return float("nan")
    return float(1.0 - np.dot(x, y) / denom)


def mahalanobis_distance(x, y, inv_cov):
    d = x - y
    v = float(np.dot(np.dot(d, inv_cov), d))
    return float(np.sqrt(max(v, 0.0)))


def summary_stats(values):
    arr = np.array(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if len(arr) == 0:
        return {"n": 0, "mean": float("nan"), "std": float("nan")}
    return {"n": len(arr), "mean": float(np.mean(arr)), "std": float(np.std(arr))}


def run_geometric_eval(features_dir, layer, n_pairs, seed, cov_reg):
    base = Path(features_dir)
    shared = np.load(base / "labels_domains_ids.npz", allow_pickle=True)
    y = shared["y"].astype(int)
    X = np.load(base / f"layer_{int(layer):02d}.npz")["X"]

    idx0 = np.where(y == 0)[0]
    idx1 = np.where(y == 1)[0]

    pairs00 = sample_pairs(idx0, idx0, n_pairs, seed + 1)
    pairs11 = sample_pairs(idx1, idx1, n_pairs, seed + 2)
    pairs01 = sample_pairs(idx0, idx1, n_pairs, seed + 3)

    cov = np.cov(X, rowvar=False) + cov_reg * np.eye(X.shape[1])
    inv_cov = np.linalg.pinv(cov)

    cos00 = [cosine_distance(X[i], X[j]) for i, j in pairs00]
    cos11 = [cosine_distance(X[i], X[j]) for i, j in pairs11]
    cos01 = [cosine_distance(X[i], X[j]) for i, j in pairs01]
    mah00 = [mahalanobis_distance(X[i], X[j], inv_cov) for i, j in pairs00]
    mah11 = [mahalanobis_distance(X[i], X[j], inv_cov) for i, j in pairs11]
    mah01 = [mahalanobis_distance(X[i], X[j], inv_cov) for i, j in pairs01]

    pca = PCA(n_components=2, random_state=seed)
    proj = pca.fit_transform(X)

    fig, ax = plt.subplots(figsize=(8, 6))
    m0 = y == 0
    m1 = y == 1
    ax.scatter(proj[m0, 0], proj[m0, 1], s=12, alpha=0.6, label="label=0 (false)")
    ax.scatter(proj[m1, 0], proj[m1, 1], s=12, alpha=0.6, label="label=1 (true)")
    ax.set_title(f"PCA Projection (Layer {int(layer):02d})")
    ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0] * 100:.2f}% var)")
    ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1] * 100:.2f}% var)")
    ax.legend(loc="best")
    ax.grid(alpha=0.2)
    fig.tight_layout()
    plt.show()

    print(f"\n--- Distance Summary (Layer {layer}) ---")
    print(f"Cosine  | within-0: {summary_stats(cos00)['mean']:.4f}  within-1: {summary_stats(cos11)['mean']:.4f}  between: {summary_stats(cos01)['mean']:.4f}")
    print(f"Mahal.  | within-0: {summary_stats(mah00)['mean']:.4f}  within-1: {summary_stats(mah11)['mean']:.4f}  between: {summary_stats(mah01)['mean']:.4f}")

    return {
        "layer": layer,
        "pca_explained_variance_ratio": pca.explained_variance_ratio_.tolist(),
        "cosine": {"within_0": summary_stats(cos00), "within_1": summary_stats(cos11), "between": summary_stats(cos01)},
        "mahalanobis": {"within_0": summary_stats(mah00), "within_1": summary_stats(mah11), "between": summary_stats(mah01)},
    }

In [ ]:
print(f"Running geometric eval on best layer: {BEST_LAYER}")
geo_results = run_geometric_eval(FEATURES_DIR, layer=BEST_LAYER, n_pairs=N_PAIRS, seed=SEED, cov_reg=COV_REG)

## Step 5: Summary & Download
View final results and download outputs.

In [ ]:
print("=" * 60)
print("LAYER SWEEP SUMMARY")
print("=" * 60)
print(sweep_df.to_string(index=False))

print(f"\nBest layer: {BEST_LAYER}")
print(f"Best test AUROC: {best_row['test_auroc']:.4f}")
print(f"Best test accuracy: {best_row['test_acc']:.4f}")

majority_class_ratio = max(sweep_df.iloc[0]['n_train'], sweep_df.iloc[0]['n_test']) / (sweep_df.iloc[0]['n_train'] + sweep_df.iloc[0]['n_test'])
print(f"\nNote: Check label balance in your dataset. If imbalanced, AUROC is more reliable than accuracy.")

In [ ]:
import shutil

shutil.make_archive("features", "zip", ".", FEATURES_DIR)
print("Created features.zip")

from google.colab import files
files.download("layer_sweep_results.csv")
files.download("domain_ablation_results.csv")
files.download("features.zip")

# step 6
Check for Non-Linear features

In [ ]:
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader, WeightedRandomSampler


MLP_HIDDEN_SIZE = 32 # changed from 256
MLP_DROPOUT = 0.3
MLP_LR = 1e-3
MLP_WEIGHT_DECAY = 1e-4
MLP_EPOCHS = 50
MLP_BATCH = 256


class _MLPNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, dropout):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)


class MLPProbe:
    """Thin wrapper so eval_binary_classifier can call .predict_proba()."""

    def __init__(self, input_dim, hidden_dim=256, dropout=0.3, lr=1e-3,
                 weight_decay=1e-4, epochs=50, batch_size=256, seed=42, device="cpu"):
        torch.manual_seed(seed)
        self.device = torch.device(device)
        self.model = _MLPNet(input_dim, hidden_dim, dropout).to(self.device)
        self.lr = lr
        self.weight_decay = weight_decay
        self.epochs = epochs
        self.batch_size = batch_size

    def fit(self, X, y):
        self.model.train()
        ds = TensorDataset(torch.tensor(X, dtype=torch.float32), torch.tensor(y, dtype=torch.float32))

        n_pos = float(y.sum())
        n_neg = float(len(y) - n_pos)
        sample_weights = np.where(y == 1, 1.0 / n_pos, 1.0 / n_neg)
        sampler = WeightedRandomSampler(sample_weights, num_samples=len(y), replacement=True)
        loader = DataLoader(ds, batch_size=self.batch_size, sampler=sampler)

        opt = torch.optim.Adam(self.model.parameters(), lr=self.lr, weight_decay=self.weight_decay)
        loss_fn = nn.BCEWithLogitsLoss()

        for epoch in range(self.epochs):
            for xb, yb in loader:
                xb, yb = xb.to(self.device), yb.to(self.device)
                opt.zero_grad()
                loss_fn(self.model(xb), yb).backward()
                opt.step()
        return self

    def predict_proba(self, X):
        self.model.eval()
        with torch.no_grad():
            logits = self.model(torch.tensor(X, dtype=torch.float32).to(self.device))
            p1 = torch.sigmoid(logits).cpu().numpy()
        return np.column_stack([1 - p1, p1])


def run_mlp_sweep(features_dir, test_size, seed, hidden_size, dropout, device):
    features_path = Path(features_dir)
    shared = np.load(features_path / "labels_domains_ids.npz", allow_pickle=True)
    y = shared["y"]

    train_idx, test_idx = build_train_test_indices(len(y), test_size, seed)

    layer_files = sorted(features_path.glob("layer_*.npz"), key=lambda p: int(p.stem.split("_")[1]))
    print(f"MLP Probe: {len(layer_files)} layers, hidden={hidden_size}, dropout={dropout}, device={device}")
    print(f"  n_train={len(train_idx)}, n_test={len(test_idx)}")

    rows = []
    for layer_file in layer_files:
        layer_idx = int(layer_file.stem.split("_")[1])
        X = np.load(layer_file)["X"]

        clf = MLPProbe(
            input_dim=X.shape[1], hidden_dim=hidden_size, dropout=dropout,
            lr=MLP_LR, weight_decay=MLP_WEIGHT_DECAY, epochs=MLP_EPOCHS,
            batch_size=MLP_BATCH, seed=seed, device=device,
        ).fit(X[train_idx], y[train_idx])

        train_m = eval_binary_classifier(clf, X[train_idx], y[train_idx])
        test_m = eval_binary_classifier(clf, X[test_idx], y[test_idx])

        row = {
            "layer": layer_idx, "n_train": len(train_idx), "n_test": len(test_idx),
            "train_acc": train_m["acc"], "train_auroc": train_m["auroc"],
            "test_acc": test_m["acc"], "test_auroc": test_m["auroc"],
        }
        rows.append(row)
        print(f"  layer={layer_idx:02d}  train_acc={row['train_acc']:.4f}  train_auroc={row['train_auroc']:.4f}  test_acc={row['test_acc']:.4f}  test_auroc={row['test_auroc']:.4f}")

    return pd.DataFrame(rows).sort_values("layer").reset_index(drop=True)

In [ ]:
mlp_df = run_mlp_sweep(FEATURES_DIR, test_size=TEST_SIZE, seed=SEED, hidden_size=MLP_HIDDEN_SIZE, dropout=MLP_DROPOUT, device=DEVICE)

mlp_best = mlp_df.loc[mlp_df["test_auroc"].idxmax()]
print(f"\nMLP best layer: {int(mlp_best['layer'])} (test_auroc={mlp_best['test_auroc']:.4f})")
print(f"LR  best layer: {BEST_LAYER} (test_auroc={best_row['test_auroc']:.4f})")
print(f"MLP improvement over LR: {mlp_best['test_auroc'] - best_row['test_auroc']:+.4f}")

mlp_df.to_csv("mlp_sweep_results_enhanced_overfitting_measures.csv", index=False)
print("Saved mlp_sweep_results_enhanced_overfitting_measures.csv")
mlp_df

MLP Probe: 41 layers, hidden=256, dropout=0.3, device=cuda
  n_train=7542, n_test=1885
  layer=00  train_acc=0.6928  train_auroc=0.7873  test_acc=0.5655  test_auroc=0.5556
  layer=01  train_acc=0.7690  train_auroc=0.8860  test_acc=0.5496  test_auroc=0.5736
  layer=02  train_acc=0.8457  train_auroc=0.9456  test_acc=0.5671  test_auroc=0.5745
  layer=03  train_acc=0.8937  train_auroc=0.9723  test_acc=0.5629  test_auroc=0.5647
  layer=04  train_acc=0.9427  train_auroc=0.9901  test_acc=0.5851  test_auroc=0.5899
  layer=05  train_acc=0.9483  train_auroc=0.9923  test_acc=0.5989  test_auroc=0.6051
  layer=06  train_acc=0.9643  train_auroc=0.9964  test_acc=0.5889  test_auroc=0.6026
  layer=07  train_acc=0.9752  train_auroc=0.9968  test_acc=0.6127  test_auroc=0.6209
  layer=08  train_acc=0.9822  train_auroc=0.9974  test_acc=0.6207  test_auroc=0.6321
  layer=09  train_acc=0.9869  train_auroc=0.9989  test_acc=0.6186  test_auroc=0.6325
  layer=10  train_acc=0.9909  train_auroc=0.9995  test_acc=0.6292  test_auroc=0.6582
  layer=11  train_acc=0.9898  train_auroc=0.9993  test_acc=0.6371  test_auroc=0.6602
  layer=12  train_acc=0.9943  train_auroc=0.9996  test_acc=0.6552  test_auroc=0.6806
  layer=13  train_acc=0.9940  train_auroc=0.9995  test_acc=0.6642  test_auroc=0.6904
  layer=14  train_acc=0.9936  train_auroc=0.9995  test_acc=0.6679  test_auroc=0.6979
  layer=15  train_acc=0.9891  train_auroc=0.9996  test_acc=0.6594  test_auroc=0.7026
  layer=16  train_acc=0.9935  train_auroc=0.9998  test_acc=0.6743  test_auroc=0.7069
  layer=17  train_acc=0.9926  train_auroc=0.9997  test_acc=0.6870  test_auroc=0.7175
  layer=18  train_acc=0.9940  train_auroc=0.9997  test_acc=0.6833  test_auroc=0.7085
  layer=19  train_acc=0.9936  train_auroc=0.9996  test_acc=0.6854  test_auroc=0.7079
  layer=20  train_acc=0.9905  train_auroc=0.9996  test_acc=0.6700  test_auroc=0.7025
  layer=21  train_acc=0.9875  train_auroc=0.9994  test_acc=0.6679  test_auroc=0.7021
  layer=22  train_acc=0.9907  train_auroc=0.9995  test_acc=0.6653  test_auroc=0.6948
  layer=23  train_acc=0.9816  train_auroc=0.9991  test_acc=0.6504  test_auroc=0.6946
  layer=24  train_acc=0.9905  train_auroc=0.9995  test_acc=0.6716  test_auroc=0.6932
  layer=25  train_acc=0.9910  train_auroc=0.9995  test_acc=0.6653  test_auroc=0.6863
  layer=26  train_acc=0.9885  train_auroc=0.9991  test_acc=0.6594  test_auroc=0.6846
  layer=27  train_acc=0.9922  train_auroc=0.9996  test_acc=0.6637  test_auroc=0.6844
  layer=28  train_acc=0.9889  train_auroc=0.9996  test_acc=0.6562  test_auroc=0.6808
  layer=29  train_acc=0.9903  train_auroc=0.9993  test_acc=0.6663  test_auroc=0.6850
  layer=30  train_acc=0.9874  train_auroc=0.9995  test_acc=0.6700  test_auroc=0.6877
  layer=31  train_acc=0.9879  train_auroc=0.9997  test_acc=0.6642  test_auroc=0.6806
  layer=32  train_acc=0.9881  train_auroc=0.9994  test_acc=0.6536  test_auroc=0.6781
  layer=33  train_acc=0.9914  train_auroc=0.9997  test_acc=0.6642  test_auroc=0.6861
  layer=34  train_acc=0.9890  train_auroc=0.9994  test_acc=0.6695  test_auroc=0.6905
  layer=35  train_acc=0.9897  train_auroc=0.9995  test_acc=0.6716  test_auroc=0.6847
  layer=36  train_acc=0.9902  train_auroc=0.9996  test_acc=0.6610  test_auroc=0.6797
  layer=37  train_acc=0.9753  train_auroc=0.9988  test_acc=0.6477  test_auroc=0.6780
  layer=38  train_acc=0.9846  train_auroc=0.9991  test_acc=0.6780  test_auroc=0.6890
  layer=39  train_acc=0.9671  train_auroc=0.9957  test_acc=0.6599  test_auroc=0.6736
  layer=40  train_acc=0.9909  train_auroc=0.9998  test_acc=0.6531  test_auroc=0.6796

MLP best layer: 17 (test_auroc=0.7175)
LR  best layer: 17 (test_auroc=0.6589)
MLP improvement over LR: +0.0586
Saved mlp_sweep_results.csv

    layer  n_train  n_test  train_acc  train_auroc  test_acc  test_auroc
0       0     7542    1885   0.692787     0.787288  0.565517    0.555630
1       1     7542    1885   0.769027     0.885972  0.549602    0.573591
2       2     7542    1885   0.845664     0.945646  0.567109    0.574522
3       3     7542    1885   0.893662     0.972349  0.562865    0.564666
4       4     7542    1885   0.942721     0.990130  0.585146    0.589874
5       5     7542    1885   0.948290     0.992328  0.598939    0.605112
6       6     7542    1885   0.964333     0.996379  0.588859    0.602557
7       7     7542    1885   0.975206     0.996777  0.612732    0.620894
8       8     7542    1885   0.982233     0.997356  0.620690    0.632143
9       9     7542    1885   0.986874     0.998863  0.618568    0.632520
10     10     7542    1885   0.990851     0.999461  0.629178    0.658182
11     11     7542    1885   0.989791     0.999337  0.637135    0.660207
12     12     7542    1885   0.994299     0.999590  0.655172    0.680566
13     13     7542    1885   0.994033     0.999492  0.664191    0.690356
14     14     7542    1885   0.993636     0.999531  0.667905    0.697873
15     15     7542    1885   0.989128     0.999619  0.659416    0.702626
16     16     7542    1885   0.993503     0.999831  0.674271    0.706896
17     17     7542    1885   0.992575     0.999658  0.687003    0.717515
18     18     7542    1885   0.994033     0.999672  0.683289    0.708461
19     19     7542    1885   0.993636     0.999599  0.685411    0.707905
20     20     7542    1885   0.990453     0.999637  0.670027    0.702500
21     21     7542    1885   0.987536     0.999355  0.667905    0.702126
22     22     7542    1885   0.990719     0.999517  0.665252    0.694817
23     23     7542    1885   0.981570     0.999146  0.650398    0.694575
24     24     7542    1885   0.990453     0.999451  0.671618    0.693162
25     25     7542    1885   0.990984     0.999525  0.665252    0.686273
26     26     7542    1885   0.988465     0.999056  0.659416    0.684560
27     27     7542    1885   0.992177     0.999588  0.663660    0.684441
28     28     7542    1885   0.988862     0.999586  0.656233    0.680828
29     29     7542    1885   0.990321     0.999302  0.666313    0.685003
30     30     7542    1885   0.987404     0.999489  0.670027    0.687658
31     31     7542    1885   0.987934     0.999660  0.664191    0.680597
32     32     7542    1885   0.988067     0.999369  0.653581    0.678134
33     33     7542    1885   0.991382     0.999726  0.664191    0.686095
34     34     7542    1885   0.988995     0.999427  0.669496    0.690520
35     35     7542    1885   0.989658     0.999525  0.671618    0.684724
36     36     7542    1885   0.990188     0.999640  0.661008    0.679699
37     37     7542    1885   0.975338     0.998752  0.647745    0.677957
38     38     7542    1885   0.984619     0.999139  0.677984    0.688980
39     39     7542    1885   0.967117     0.995749  0.659947    0.673557
40     40     7542    1885   0.990851     0.999837  0.653050    0.679600

# Data Collection Pipeline

As of 3/10/2026 at 7PM recall:

1: We want to run experiments that check if the model's predicted truth value matches the true truth value

2: Afterwards we are considering grabbing the model's activations to investigate its internal state during various true/false tasks

The above pipeline combined a lot of disjoint steps into functions as a design choice because we only wanted to examine BoolQ. Now we may want to look at arbitrary T/F datasets, so I have written some helper functions

In [ ]:
# This function is essentially just a wrapper around the logic of getting a row/column in parquet/csv files. It will be called so
# much below that I wrote a helper function for it
def extract_dataset_feature(dataset_path : str, statement_label,dataset_type="csv"):
    # I saw we were using parquet files but most of the datasets we want to use are in csv format. Since it's a one-time read with data being moved to other formats,
    # I figure it's fine to use either so there is an option here to use csv or parquet
    dataset = ""
    if dataset_type == "csv":
      dataset = pd.read_csv(dataset_path)
    elif dataset_type == "parquet":
      dataset = pd.read_parquet(dataset_path)
    else:
      raise ValueError(f"Unsupported dataset type: {dataset_type}")

    statements = dataset[statement_label]
    return statements.tolist()

# Example testing with BoolQ: It works
# print(extract_dataset_feature(DATASET_PATH,"statement",dataset_type="parquet"))

['do iran and afghanistan speak the same language', 'do good samaritan laws protect those who help at an accident', 'is windows movie maker part of windows essentials', 'is confectionary sugar the same as powdered sugar', 'is elder scrolls online the same as skyrim', 'can you use oyster card at epsom station', "will there be a season 4 of da vinci's demons", 'is the federal court the same as the supreme court', 'did abraham lincoln write the letter in saving private ryan', 'is batman and robin a sequel to batman forever', 'is a wolverine the same as a badger', 'will there be a green lantern 2 movie', 'does the icc has jurisdiction in the united states', 'calcium carbide cac2 is the raw material for the production of acetylene', 'is there a now you see me 3 coming out', 'does a penalty shoot out goal count towards the golden boot', 'will there be a new season of cutthroat kitchen', 'is jack sikma in the hall of fame', 'can elves and humans mate lord of the rings', 'the boy in the plastic bubble based on true story', 'science begins with the premise that knowledge should first be acquired through observation', 'is tim brown in the hall of fame', 'can you drink alcohol in public in denmark', 'is jersey currency legal tender in the uk', 'have the milwaukee bucks ever won a championship', 'does the world cup final go to penalties', 'is kingdom manga based on a true story', 'is croatia part of the european economic area', 'can u marry a dead person in france', 'is saline and sodium chloride the same thing', 'is there a treatment for the bubonic plague', "does buffy's mom know she's a slayer", 'was the leaning tower of pisa built leaning', "is the movie fool's gold a true story", 'has any nfl team played the superbowl at home', 'does each australian state have its own constitution', 'can you have a right and left bundle branch block', 'do you always have to say check in chess', 'is an australian shepherd the same as an australian cattle dog', 'is tomato puree and tomato sauce the same thing', 'is the blues brothers based on a true story', 'is newcastle upon tyne the same as newcastle', 'is post office and royal mail the same', 'has any supreme court nominee not been confirmed', 'is thanksgiving always the last thursday of the month', 'is lord of the rings after the hobbit', 'is the fallen movie going to have a sequel', 'does anyone on instagram have 1 billion followers', 'in the phantom menace is padme the queen', 'is lord of the rings considered an epic', 'does the euro sign go before the number', 'can stainless steel be used on induction cooktop', 'is job termination the same as being fired', 'does age have any influence on attentional ability or inattentional blindness', 'is sanskrit the first language of the world', 'is a jack russell considered a small breed', 'does air force one travel with fighter escort', 'is it legal to own an ar15 in california', 'is the national anthem and star spangled banner the same', 'is there an international airport in naples italy', 'can you buy cadburys creme eggs all year round', 'do homologous chromosomes carry information for the same traits', 'has michigan ever won a national championship in football', 'you can tell a lot about a person by how they treat their waiter', 'are there any crocodiles native to north america', 'does lex luthor know who superman is in smallville', 'do you have to have a college degree to take the bar exam', "will there be a season 2 of marvel's iron fist", 'is 844 a toll free number in canada', 'does any other country have daylight savings time', 'has anyone ever pitched back to back no hitters', 'is there a black bike week in myrtle beach', 'are static shock and black lightning the same person', 'is there such a thing as unbreakable glass', 'can liquid latex be used as an adhesive', 'is it illegal to carry a pistol in your car in texas', 'is it legal to carry a sgian dubh', 'several cranial nerves innervate structures of the tongue', 'is porto rico a part of the united states', 'is there sales tax in the state of washington', 'has anyone scored 6 goals in one game', 'can puppies see right when their eyes open', 'is the sears tower the same as the hancock building', 'is tokyo ghoul re related to tokyo ghoul', 'do texas state troopers have to wear hats', 'is vaping illegal if you are under 18', 'is wheat flour and white flour the same thing', 'do they find the body in stand by me', 'did the english win the hundred years war', 'is ferguson jenkins in the hall of fame', 'are family dollar and dollar general the same company', "is station 19 a grey's anatomy spin off", 'are tomatoes a member of the nightshade family', 'is dollar tree the same as dollar general', 'does the cat in the hat have a name', 'the movie rudy based on a true story', 'is the movie the wall a true story', 'is it legal to carry a gun in nyc', 'the former soviet union broke into separate states', 'does hot and sour soup have a lot of sodium', 'would a person sink in a corn silo', 'paths from the cerebral cortex to the spinal cord are called the corticospinal tracts', 'do you have to bounce the ball in afl', 'is a denatured protein still able to function', 'is the movie the mountain between us based on a real story', 'do you have to pay taxes in the united states', 'are the marines part of the us navy', 'does liquid coffee mate have to be refrigerated', 'will there be a uk general election in 2018', 'can i use dexron iii for dexron ii', 'can i own a handgun in the uk', 'can you have two jobs in south africa', 'are long term capital gains taxed at a lower rate', 'does oregon have the stand your ground law', 'are pumas cougars and mountain lions the same animal', 'is popeye the sailor man a disney character', 'has tom hanks ever won an academy award', 'is jim hart in the hall of fame', 'do you need a gun license to buy a gun in nj', 'is it legal to drink in public in london', 'do you have to register to vote in america', 'are chess pie and buttermilk pie the same', 'true or false anaphylaxis generally only affects the skin and eyes', 'do you need to fast for random glucose test', 'is there going to be a season 4 of the border', 'does the nissan rogue have all wheel drive', 'is fear the walking dead set before the walking dead', 'do new zealand and australia have the same flag', 'did austria qualify for the world cup 2018', 'is carrie underwood in the movie soul surfer', "is there a difference between saline and lactated ringer's", "is one flew over the cuckoo's nest a true story", 'do you put water in a fog machine', 'when sandy hit nj was it a hurricane', 'is there an age limit to run for congress', 'during his lifetime an athenian citizen could serve on the council of five hundred', 'was call me by your name a book', 'has england won any world cup in cricket', 'is watcher in the woods a disney movie', 'do supreme court judges get secret service protection', 'was the movie dunkirk based on a book', 'does a jury have to be unanimous uk', 'is national guard boot camp the same as army', 'do dogwood trees grow in the middle east', 'is there such a thing as a coywolf', 'are doc martens still made in the uk', 'would hydrogen chloride be a gas at room temperature', 'is it possible to build an alcohol tolerance', 'do blue jays take over other birds nests', 'is the olympic torch always lit in greece', 'is canada in the 2018 soccer world cup', 'can cradle cap make baby hair fall out', 'is king louie in the jungle book book', 'does drake in my feelings have a video', 'can goalie pick up ball from throw in', 'is the cecil hotel still open in los angeles', 'is a birth certificate a valid form of id', 'is there a town named keister in the united states', 'do the individual parallel lines in a parallel circuit have different currents flowing through them', 'is the orientation of a protein sequence important for the protein function', 'is dc legends of tomorrow based on a comic', 'is bok choy the same as pak choi', 'do guinea pigs come from papua new guinea', 'is trelane a member of the q continuum', 'did thomas jefferson wrote the declaration of independence when he was president', 'was season 8 of vampire diaries the last', 'is antioch ca part of the bay area', 'is st. patricks day always on march 17', 'is there a national bring your dog to work day', 'does the iphone 8 plus have touch id', 'is there a fourth book of magnus chase', 'can you buy beer on sunday in new york', 'is there going to be a my little pony season 8', 'does a goal from a throw in count', 'the visual cliff is a device for studying', 'is it possible to download all of wikipedia', 'the long road home is it a series', 'do you need to put return address on mail', 'is guillain barre syndrome a lower motor neuron disease', 'is there a second season of iron fist', 'is himalaya the highest mountain in the world', 'is a 1-888 number toll free', 'is the graviton part of the standard model', "is st david's day a bank holiday in wales", 'are the normal force and force of gravity always equal', 'does the mail run on memorial day weekend', 'is season 7 of ahs the last season', 'can you get drafted out of high school into the nba', 'did dan stevens do the singing in beauty and the beast', 'does penalty shoot out goals count for golden boot', "is haroun and the sea of stories a children's book", 'can you play original xbox games on a 360', 'does the honda insight need to be plugged in', 'is big little lies just a mini series', 'is taylor still on the bold and beautiful', 'can you have a skunk as a pet in canada', 'can you marry your sister in the uk', 'is there going to be a season 2 of jamestown', 'does the united kingdom have an official language', 'did the dad die in the good dinosaur', 'is blue cross the same as blue shield', 'is mall of asia the biggest mall in asia', 'is 44 rem mag the same as 44 mag', 'can a person die from too much water', "does canada's worst driver lose their license", 'will there be a 13th season of criminal minds', 'are family dollar and dollar general owned by the same company', 'can you drink in the street in glasgow', 'is cheaper by the dozen a true story', 'is there such thing as a 100 pound note', 'can you inhale alcohol vapors and get drunk', 'is daylight savings time all over the world', 'is polygamy legal in any state in the united states', 'can u really hear the ocean in a shell', 'is sweet italian sausage the same as mild', 'will there be a season 3 of too close to home', 'is the medal of honor the highest honor', 'can i be sacked for falling asleep at work', 'can you buy a car in wisconsin on sunday', 'is electrode potential the same as reduction potential', 'did north korea compete in the 2018 olympics', 'was mercury used as a cure for syphilis', 'can a member of congress be removed from office', 'is london the capital of the united kingdom', 'did they actually go to hawaii in everything everything', 'can u die for drinking too much water', 'can you still win both showcases on price is right', 'is a circle the same as a sphere', 'is sperm concentration the same as sperm count', 'did ward and june cleaver sleep in the same bed', 'is canada the only country with maple trees', 'were the bodies of operation red wings recovered', 'is it normal for guys to dribble after peeing', 'can you have more than one wife in the usa', 'has there ever been a female thunderbird pilot', 'is a bba the same as a bs', 'do you need intent to commit a crime', 'is the top thrill dragster the tallest roller coaster', 'is the red cross part of the un', 'did wales ever qualify for the world cup', 'is beauty and the beast still on broadway', 'does marvel own the rights to fantastic four', 'will there be a second series of the coroner', 'is it legal to turn right on red in california', 'does bree van de kamp go to jail', 'do penalties after extra time count towards golden boot', 'is there really such a thing as a broken heart', 'if a table contains a primary key there can be no duplicate records in a table', 'have the arkansas razorbacks ever won a national championship in football', "do litigants on people's court get paid", 'is zip code the same as post code', 'did we leave the lunar rover on the moon', 'is it legal to drink beer while driving in texas', 'does blow drying your hair kill lice eggs', 'was the movie the guardian based on a true story', 'did lebanon ever qualify for the world cup', 'is monaco a country in its own right', 'is the movie the mission based on a true story', 'do you have to win a tennis set by 2', 'did china ever qualify for fifa world cup', 'are england in the world cup semi finals', 'are green beans the same as french beans', 'does all of japan have the same time zone', 'is spiderman homecoming a sequel to the amazing spider man', 'does the entire blastocyst develop into a fetus', 'can someone be both left and right handed', 'is there a season 4 of phryne fisher', 'can you go out with a wild card in uno', 'can a us citizen hold a foreign title', 'can a social security number have 8 digits', 'has anyone won all four grand slam in one year', 'can you download itv hub on xbox 360', 'does a trapezoid have one set of parallel lines', 'does prime minister have to be an mp', 'can i use my veteran id to get on base', 'is it illegal to be in possession of alcohol under 21', 'is the 2017 chevy cruze front wheel drive', 'can there be a beach on a lake', 'does puerto rico have to follow us laws', 'does every us citizen have a social security number', 'can anything be faster than the speed of light', 'is there going to be a mr robot season 4', 'is it possible for an element to have different types of atoms', 'is a cougar and a mountain lion the same thing', 'does jimmy o die in sons of anarchy', 'is triamcinolone acetonide cream used to treat poison ivy', 'will an xbox 360 game work on an xbox one', 'is there such thing as a jack rabbit', 'are they coming out with a new tinkerbell movie', 'are cash money and money mart the same company', 'is it ok to eat cooking apples raw', 'does the texas flag fly at the same height as the american flag', 'is it ordinary time in the catholic church', 'does borderlands 2 handsome collection have all dlc', 'is there going to be a season 3 of project runway junior', 'is transit aba number the same as routing number', 'is hashtag the same as the number sign', 'does the f train stop at queens plaza', 'is there a difference between slugs and snails', 'was the french quarter affected by hurricane katrina', 'can one point be in two different planes', 'do professional soccer players play in the olympics', 'is the avengers and avengers assemble the same film', 'is there going to be a season 8 of rules of engagement', 'are liquor stores open on sunday in wv', 'is there still a royal family in spain', 'is the limbic system the oldest part of the brain', "are target and macy's owned by the same company", 'did bonnie blairs daughter make the olympic team', 'is the baby in fuller house a twin', 'was tom holland in amazing spider man 2', 'is stella the mother on how i met your mother', 'can an aftershock be stronger than an earthquake', 'are there any wild ravens in the uk', 'is a hyundai genesis coupe a sports car', 'does a death certificate have to show cause of death', 'is it legal to carry a gun in new hampshire', 'can you have identical twins that are different genders', 'is there a season 5 for the flash', 'is the girl in the spiders web a sequel to the girl with the dragon tattoo', 'was the movie 300 based on real events', 'is great britain part of the european union', 'can you send an envelope without a return address', 'is there going to be a season 5 of bates motel', 'is canada in the united states of america', 'the main component of stomach acid is sulfuric acid', 'can anyone have an out of body experience', 'is it illegal to hack into someones phone', 'does batman and harley quinn take place in the dcau', 'can a 3 way bulb work in any lamp', 'are hastings direct and hastings premier the same company', 'is the lexus es 350 front wheel drive', "is there an airport on martha's vineyard", 'were there helicopters in the second world war', 'does the us play in the world cup this year', 'is a money order the same as a postal order', 'does kaori die in your lie in april manga', 'does a macbook air have an ethernet port', 'is cornwall in the south west of england', 'can a man have more than one wife in utah', 'did the lead singer of the who have a stutter', 'does an ace beat a queen in war', 'does the switch come with 1 2 switch', 'does the mom die in the impossible movie', 'can you get aero bars in the us', 'do citizens in puerto rico pay us taxes', 'are green beans the same as string beans', 'of all the points on the production possibilities curve only one point represents an efficient point', 'was the battle of gettysburg the bloodiest battle of the civil war', 'do cows have to stay pregnant to produce milk', 'is methodist the same as church of england', 'do you get paid for being on survivor', 'will there be a second season of fairy tail', 'were all the bodies recovered from operation red wings', "is ain't a word in the webster dictionary", 'are collard greens the same as turnip greens', 'does dean come back to life in supernatural', 'is there a new robin hood movie coming out', 'did rocky beat apollo creed in rocky 1', 'is rough er part of the endomembrane system', 'is the uk part of the schengen zone', 'are there any mgm casinos in atlantic city', 'cells produce water as a by-product of energy metabolism', 'can the president serve more than two terms', 'is the cardiac sphincter the same as the lower esophageal sphincter', 'is pawn stars filmed in the actual store', 'is tomato puree the same as tomato sauce', 'is tom and jerry in the public domain', 'are the penguins out of the stanley cup', 'are you allowed to carry a knife in canada', 'does eddie murphy really sing party all the time', 'is the cash for clunkers program still active', 'is the united states coast guard part of the military', 'is there a such thing as citizens arrest', 'can you drink alcohol in salt lake city', 'do sharks die if their fins are cut off', 'is hydrated lime the same as calcium hydroxide', 'can a felon own a gun in nj', 'have the buffalo bills ever won a super bowl', 'did dennis quaid play the joker in batman', 'is a sister in law considered immediate family', 'does the empire state building have a 600th floor', 'can the house of representatives impeach a federal judge', 'is saving private ryan based on a book', 'is it illegal to pump and dump stocks', 'did italy qualify for the 2018 fifa world cup', 'can you travel to turkey with a french id card', 'inflation means specific prices are rising and relative prices are falling', 'is a set an element of its power set', "is mother's day considered a national holiday", 'do i have the right to protect myself', 'do u need a licence for an air rifle in uk', 'did gerry rafferty sing stuck in the middle with you', 'is the movie mighty joe young a true story', 'is new zealand on the other side of the world', 'can work be done in a closed system', 'do the winners of the europa league qualify for the champions league', 'does st louis still have a football team', 'is general law the same as common law', 'are all kershaw knives made in the usa', 'does an inside the park home run count as a home runs', 'do you have to turn right at a red light', 'can substrate level phosphorylation occur in the absence of oxygen', 'does switzerland give a gun to every household', 'are any of the original power rangers in the new movie', 'is a caribou the same thing as a reindeer', 'is the movie se7en based on a book', 'was the declaration of independence before the revolutionary war', 'does puerto rico vote in the us presidential election', 'can you hit the backboard on a free throw', 'is there a jaws ride at universal studios hollywood', 'will there be a new series of the durrells', 'did hurricane audr

In [ ]:
def model_output(model_name, dataset_path, out_dir, batch_size, max_length, device,
                 prompt_template, use_4bit=False):
    """Generate the model's greedy next-token for each prompt and classify as true/false.

    Saves a CSV with columns: prompt_num, answer, output, hallucination
    """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    df = pd.read_parquet(dataset_path)
    required = {"id", "domain", "label", "statement"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns: {', '.join(sorted(missing))}")

    texts = [prompt_template.format(statement=str(s)) for s in df["statement"].tolist()]
    ground_truth = df["label"].astype(int).to_numpy()
    print(f"Loaded {len(texts)} prompts")

    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    dtype = torch.float16 if device.startswith("cuda") else torch.float32

    if use_4bit and device.startswith("cuda"):
        print("Loading model with 4-bit quantization (NF4)...")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            model_name, quantization_config=bnb_config, device_map="auto",
        )
    elif device.startswith("cuda"):
        print(f"Loading model in {dtype}...")
        model = AutoModelForCausalLM.from_pretrained(
            model_name, dtype=dtype, device_map="auto",
        )
    else:
        print(f"Loading model in {dtype}...")
        model = AutoModelForCausalLM.from_pretrained(model_name, dtype=dtype)
        model.to(device)
    model.eval()
    input_device = _infer_input_device(model, fallback_device=device)
    print(f"Model loaded. Input device: {input_device}")

    results = []
    total_batches = (len(texts) + batch_size - 1) // batch_size

    for batch_num, i in enumerate(range(0, len(texts), batch_size)):
        if batch_num % 20 == 0:
            print(f"  Batch {batch_num + 1}/{total_batches}")
        batch_texts = texts[i : i + batch_size]

        enc = tokenizer(
            batch_texts, return_tensors="pt", padding=True,
            truncation=True, max_length=max_length,
        )
        enc = {k: v.to(input_device) for k, v in enc.items()}

        with torch.no_grad():
            generated_ids = model.generate(
                **enc,
                max_new_tokens=1,
                do_sample=False,
            )

        new_token_ids = generated_ids[:, enc["input_ids"].shape[1]:]
        decoded_tokens = tokenizer.batch_decode(new_token_ids, skip_special_tokens=True)

        for j, raw_output in enumerate(decoded_tokens):
            idx = i + j
            output_stripped = raw_output.strip()
            output_lower = output_stripped.lower()

            if output_lower == "true":
                model_answer = 1
            elif output_lower == "false":
                model_answer = 0
            else:
                model_answer = -1

            gt = int(ground_truth[idx])
            gt_str = "True" if gt == 1 else "False"

            if model_answer == -1:
                hallucinated = "N/A"
            else:
                hallucinated = "Yes" if model_answer != gt else "No"

            results.append({
                "prompt_num": idx,
                "answer": gt_str,
                "output": output_stripped,
                "hallucination": hallucinated,
            })

    results_df = pd.DataFrame(results)
    csv_path = out_path / "model_outputs.csv"
    results_df.to_csv(csv_path, index=False)
    print(f"\nSaved {len(results_df)} results to {csv_path}")

    valid = results_df[results_df["hallucination"] != "N/A"]
    if len(valid) > 0:
        n_hall = (valid["hallucination"] == "Yes").sum()
        print(f"Hallucination rate: {n_hall}/{len(valid)} ({100 * n_hall / len(valid):.1f}%)")
    n_na = (results_df["hallucination"] == "N/A").sum()
    if n_na > 0:
        print(f"Unrecognized outputs (not true/false): {n_na}")
        print("Sample unrecognized:", results_df[results_df["hallucination"] == "N/A"]["output"].value_counts().head(10).to_dict())

    return results_df

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 152)

## Step 7: Model Output & Hallucination Detection
Use `model.generate` to get the model's greedy next-token prediction for each prompt, classify it as True/False, and flag hallucinations where the model's answer disagrees with ground truth.

In [ ]:
OUTPUT_DIR = "model_outputs"
PROMPT_TEMPLATE_TF = "True or False: {statement}\nAnswer:"

output_df = model_output(
    model_name=MODEL_NAME,
    dataset_path=DATASET_PATH,
    out_dir=OUTPUT_DIR,
    batch_size=BATCH_SIZE,
    max_length=MAX_LENGTH,
    device=DEVICE,
    prompt_template=PROMPT_TEMPLATE_TF,
    use_4bit=USE_4BIT,
)

print("\n--- First 20 rows ---")
print(output_df.head(20).to_string(index=False))
print(f"\n--- Output value counts ---")
print(output_df["output"].value_counts().head(15))
print(f"\n--- Hallucination breakdown ---")
print(output_df["hallucination"].value_counts())

from google.colab import files
files.download(f"{OUTPUT_DIR}/model_outputs.csv")